/*
[DATE]          2020-06-08
[ORGANISATION]  Utrecht University
[EMPLOYEE]      Arjan Sieverink
[CONTACT1]      https://www.uu.nl/staff/JASieverink
[REMARKS]       Clear database tables and views
*/
USE PUREP_Staging
GO

DROP TABLE dbo.INTERNAL_PARTICIPANTS
DROP TABLE dbo.INTERNAL_PROJECT_ORGANISATIONS
DROP TABLE dbo.ORGANISATION_DATA
DROP TABLE dbo.ORGANISATION_HIERARCHY
DROP TABLE dbo.ORGANISATION_NAME_VARIANTS
DROP TABLE dbo.PERSON_PHOTO_INFORMATION
DROP TABLE dbo.PERSON_PROFILE_INFORMATION
DROP TABLE dbo.PERSON_SAPDATA
DROP TABLE dbo.PROJECT_DATA
DROP TABLE dbo.PROJECT_IDS
DROP TABLE dbo.PROJECT_KEYWORDS
DROP TABLE dbo.PROJECT_PROJECT_RELATION
DROP TABLE dbo.PROJECT_UPMPROJECTTYPES
DROP TABLE dbo.STAFF_ORGANISATION_RELATION
GO

DROP VIEW dbo.PERSON_DATA
DROP VIEW dbo.PERSON_NAMES
DROP VIEW dbo.PERSON_PHOTOS
DROP VIEW dbo.PERSON_PROFILES
DROP VIEW dbo.PERSON_TITLES
DROP VIEW dbo.PROJECT_DATA_PLUS
DROP VIEW dbo.STAFF_PERSON_COMMS
GO
