CREATE TABLE [dbo].[INTERNAL_PARTICIPANTS] (
    [PROJECT_ID]                    NVARCHAR (1024) NOT NULL,
    [PERSON_ID]                     NVARCHAR (1024) NOT NULL,
    [ORGANISATION_ID]               NVARCHAR (1024) NOT NULL,
    [ROLE]                          NVARCHAR (1024) NOT NULL,
    [PLANNED_RESEARCHER_COMMITMENT] FLOAT (53)      NULL,
    [ASSOCIATION_PERIOD_START_DATE] DATE            NULL,
    [ASSOCIATION_PERIOD_END_DATE]   DATE            NULL
);

