CREATE TABLE [dbo].[ORGANISATION_HIERARCHY] (
    [PARENT_ORGANISATION_ID] NVARCHAR (255) NOT NULL,
    [CHILD_ORGANISATION_ID]  NVARCHAR (255) NOT NULL,
    [START_DATE]             DATE           NULL,
    [END_DATE]               DATE           NULL
);

