CREATE TABLE [dbo].[PERSON_SAPDATA] (
    [PERSON_ID]           NVARCHAR (255) NOT NULL,
    [USERNAME]            NVARCHAR (255) NULL,
    [TITLE]               NVARCHAR (255) NULL,
    [POST_NOMINALS]       NVARCHAR (255) NULL,
    [FIRST_NAME]          NVARCHAR (255) NULL,
    [LAST_NAME]           NVARCHAR (255) NULL,
    [FIRST_NAME_KNOWN_AS] NVARCHAR (255) NULL,
    [LAST_NAME_KNOWN_AS]  NVARCHAR (255) NULL,
    [LAST_NAME_SORT]      NVARCHAR (255) NULL,
    [PREVIOUS_LAST_NAME]  NVARCHAR (255) NULL,
    [GENDER]              NVARCHAR (255) NULL,
    [NATIONALITY]         NVARCHAR (255) NULL,
    [EMAIL]               NVARCHAR (255) NULL,
    [DATE_OF_BIRTH]       DATE           NULL,
    [RETIRAL_DATE]        DATE           NULL
);

