CREATE TABLE [dbo].[PROJECT_KEYWORDS] (
    [TYPE]         NVARCHAR (255)  NULL,
    [PROJECT_ID]   NVARCHAR (1024) NOT NULL,
    [LOGICAL_NAME] NVARCHAR (1024) NOT NULL,
    [FREE_KEYWORD] NVARCHAR (1024) NULL
);

