CREATE TABLE [dbo].[PROJECT_PROJECT_RELATION] (
    [PROJECT_ID]        NVARCHAR (1024) NOT NULL,
    [TARGET_PROJECT_ID] NVARCHAR (1024) NOT NULL,
    [RELATION_TYPE]     NVARCHAR (1024) NOT NULL
);

